### ISSUE TITLE
Optimize Dockerfile

### ISSUE THREAD

**Issue by Feriman22** [qbittorrent/docker-qbittorrent-nox#25]
Hi,

I'd suggest one optimization in Dockerfile to reduce the size of the image, and may improve the security.

The `bash`, `curl` and `python3` packages do not need to be installed, as the qbittorrent will run perfectly well without them.

Please consider this modification, it can reduce the size of them image from 157MB to 119MB (38MB difference).

![image](https://github.com/qbittorrent/docker-qbittorrent-nox/assets/22872515/63a9f36a-9706-4884-b9d9-954b8be41701)

Thanks,
Ferenc

**Comment by Feriman22** [comment]
I have created a Docker Hub repository for it:
https://hub.docker.com/r/feriman25/qbittorrent-nox-reduced

You can test it for yourself, if you want, it works well for me.

**Comment by Chocobo1** [comment]
>The bash, curl and python3 packages do not need to be installed, as the qbittorrent will run perfectly well without them.

* `python3`
  This is required for the 'search engine' functionality in qbt.
 * `bash`, `curl`
   These are included for the 'Run external programs' functionality in qbt. They are not strictly required but they are extremely popular among users. And since they only take minuscule space, they are included for the user convenience.

Thanks for the interest.
