### ISSUE TITLE
UI broken after upgrading to v5

### ISSUE THREAD

**Issue by myleshk** [qbittorrent/docker-qbittorrent-nox#48]
The UI is broken.
- it's cropped at the top
- Clicking all the buttons has no effect, only the menu will expand, but that's it.

<img width="1511" alt="Screenshot 2024-10-16 at 10 45 30 PM" src="https://github.com/user-attachments/assets/71f29fdd-97b9-4b71-9e58-392c7bd98704">

# Attempts
- clear cache, change browser, etc.: still broken
- downgrade to v4.x: working fine again

**Comment by victorpinal** [comment]
try cleaning browser cache, i solved some UI errors that way

**Comment by Chocobo1** [comment]
@myleshk 
Does your browser console show any error?

**Comment by myleshk** [comment]
I don't remember I saw any error in the console. But I'll confirm if I have time...

**Comment by arkandias** [comment]
Check this issue (and those linked in the discussion): https://github.com/qbittorrent/qBittorrent/issues/21703

There are two separate problem:
- on Safari (at least), the height of the main div is set to 0px; this will be fixed in the next release, meanwhile you can refresh the page to fix it (you'll have to do this every time the page reloads) ;
- the horizontal splitter is always on top by default, so you have to drag it down every time the page refreshes (this has been fixed in v5.0.1).

**Comment by Chocobo1** [comment]
>Check this issue (and those linked in the discussion): https://github.com/qbittorrent/qBittorrent/issues/21703

So it is a upstream issue. Closing this issue and track upstream instead.
